# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 03:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20160323_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
